### ISSUE TITLE
Baseline: Setup Experiment Tracking

### ISSUE THREAD

**Issue by wp99cp** [wp99cp/continual-learning#1]
We should set up proper experiment tracking using [TensorBoard](https://www.tensorflow.org/tensorboard).

## Tasks:

- [x] track all important stats (LR, Loss, ...)
- [x] track classes and splits
- [x] track all evaluation data
